### ISSUE TITLE
SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by natanfelles** [jekylltools/jekyll-tipue-search#12]
The file `tipuesearch_content.js` has no an layout defined than Jekyll 3.4.3 is using the other layout, the `default` in my case.

This issue make the generated JS file with HTML content. Than the javascript break. The output error is  `SyntaxError: expected expression, got '<'` why the build file starts with the default template, `<DOCTYPE html...`.

To solve this I added a variable in the liquid `tipuesearch_content.js`.

The header as follow:

```yml
---
# Content index for Tipue Search
# https://github.com/jekylltools/jekyll-tipue-search
# v1.2
layout: null
---
```

It is "simple" but avoid this error. Perhaps you can add it by default. Thank you!

**Comment by jekylltools** [comment]
This makes senses. thanks for your help!
