### ISSUE TITLE
Live Mode

### ISSUE THREAD

**Issue by natanfelles** [jekylltools/jekyll-tipue-search#15]
Ok.  It can be very, very slow...

I tested the live mode here adding the following code in the bottom of the file `tipuesearch_content.js`.

```js
var tipuesearch_pages = [];
$.each(tipuesearch.pages, function (k,v){
  tipuesearch_pages[k] = v.url;
});
```

Personally, I am not using it now. But, when I changed the `mode` to `live` my page breaks. Then I added this callback.

My question is: Is it useful to be included by default or would be best to add an option var in `_config.yml` to use the live mode, then we do not generate the content for the static mode, but only the var with the pages urls. What do you think about?

**Comment by jekylltools** [comment]
No, I don't think it is useful to be included by default. The [Tipue Search documentation states](http://www.tipue.com/search/docs/?d=5) "Live mode uses the DOM extensively, so doesn't work well with some sites, and is particularly unforgiving with malformed pages. At present, Live mode is only suitable for smaller sites with less than thirty or so pages." -- So I don't want to support it by default.  Each user can decide to use Live mode or not.
