### ISSUE TITLE
No result

### ISSUE THREAD

**Issue by marste** [jekylltools/jekyll-tipue-search#16]
Sorry, I've installed it on a blog, but it never returns a result.
Am I wrong?
http://erica.marzorati.co/search/?q=ciao

Thanks!

**Comment by jekylltools** [comment]
It appears to be working for me.

![screen shot 2017-08-22 at 17 28 17](https://user-images.githubusercontent.com/26100939/29593479-6c3a5412-875f-11e7-9838-b3c774e859f1.png)

**Comment by jekylltools** [comment]
I think you have installed it correctly! Thanks!
