### ISSUE TITLE
add whitespace control 

### ISSUE THREAD

**Issue by ghost** [jekylltools/jekyll-tipue-search#3]
add whitespace control to content index when Liquid 4 ships (hopefully in Jekyll 3.5)

https://shopify.github.io/liquid/basics/whitespace/
https://github.com/jekyll/jekyll/milestone/53

**Comment by xHN35RQ** [comment]
in `tipuesearch/tipuesearch_content.js` and `README.md#installation`

**Comment by jekylltools** [comment]
here is an example of whitespace control on `tipuesearch_content.js`: https://gist.github.com/jekylltools/6931f0d02b7edececdb258450fe2d917

If users want more minification they can use a tool like https://github.com/penibelst/jekyll-compress-html

**Comment by jekylltools** [comment]
done in 1.3
