### ISSUE TITLE
update with concat filter

### ISSUE THREAD

**Issue by ghost** [jekylltools/jekyll-tipue-search#4]
use the `concat` filter to merge tags/categories, whenever Liquid 4 ships (hopefully in Jekyll 3.5)

https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L227
https://github.com/jekyll/jekyll/milestone/53

**Comment by xHN35RQ** [comment]
using a push method for now

**Comment by jekylltools** [comment]
fixed in 1.4
