### ISSUE TITLE
Recurring linking problem

### ISSUE THREAD

**Issue by JoolianGarcia** [jekylltools/jekyll-tipue-search#9]
Hello, I'm working on implementing tipue search on [this](http://learn.neurotechedu.com/search/) site. It is built with a jekyll theme called "Feeling Responsive". I have the search form in the page, and the JSON content file generated (I can access its contents through console). However, there seems to be a problem with the ability to link the main js file to my form, I think partially because some liquid code that prepends text to all my links.
I am not sure if the problem is in the theme or in the way the search itself works. I feel a bit lost as to how I should go about debugging. I can read all the code but I am thrown off by the way jekyll compiles things.
Could you point me in a direction in which I can solve the problem?

**Comment by jekylltools** [comment]
It looks like your `url` and `baseurl` are set incorrectly. I opened an issue on your repository. https://github.com/NeuroTechX/learn.neurotechedu.com/issues/1
